
def tryInt(num,defalut):
    try:
        return int(num)
    except Exception as e:
        return defalut